name: lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install pre-commit dependency - terraform-docs
      run: |
        TF_DOCS_VER="v0.9.1"
        pushd /tmp
          curl -Lo ./terraform-docs https://github.com/terraform-docs/terraform-docs/releases/download/v0.9.1/terraform-docs-v0.9.1-$(uname | tr '[:upper:]' '[:lower:]')-amd64 && chmod +x ./terraform-docs && sudo mv ./terraform-docs /usr/bin/
        popd
    - name: Install pre-commit dependency - tflint
      uses: terraform-linters/setup-tflint@v2
    - name: Run pre-commit test
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: --all-files